prestations_prestations:
    resource: "@PrestationsBundle/Resources/config/routing/prestations.yml"
    prefix:   /prestations


prestations_homepage:
    path:     /
    defaults: { _controller: PrestationsBundle:Default:index }